### ISSUE TITLE
`OpenCodeFile` command - User friendly message needed when no path defined in config

### ISSUE THREAD

**Issue by CyrilleB79** [CyrilleB79/NVDA-Dev-Test-Toolbox#10]
### STR
On a clean config where the paths are not set:
* Open Python console
* Type the following command:
  `openCodeFile(api)`

### Actual result
Error:
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\Cyrille\AppData\Roaming\nvda\addons\nvdaDevTestToolbox\globalPlugins\ndtt\fileOpener.py", line 252, in openCodeFile
    path, line = CodeLocator(obj).getCodeLocation()
  File "C:\Users\Cyrille\AppData\Roaming\nvda\addons\nvdaDevTestToolbox\globalPlugins\ndtt\fileOpener.py", line 168, in getCodeLocation
    loc = self.getCodeLocationForModule()
  File "C:\Users\Cyrille\AppData\Roaming\nvda\addons\nvdaDevTestToolbox\globalPlugins\ndtt\fileOpener.py", line 203, in getCodeLocationForModule
    path = self.convertToSourcePath(path)
  File "C:\Users\Cyrille\AppData\Roaming\nvda\addons\nvdaDevTestToolbox\globalPlugins\ndtt\fileOpener.py", line 212, in convertToSourcePath
    return os.path.join(nvdaPath, path)
  File "ntpath.pyc", line 76, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
### Expected result
A more user friendly message/error.

**Comment by CyrilleB79** [comment]
Fixed in 4a0b4924a83450582a2f279f30577af51778012d.
