### ISSUE TITLE
Additional navigation possibilities in a log

### ISSUE THREAD

**Issue by CyrilleB79** [CyrilleB79/NVDA-Dev-Test-Toolbox#7]
The following additional navigation possibilities in the log have been suggested and discussed:

* In an error traceback: shortcut to jump to most interesting line, probably the last one.
* Same for other traceback such as stack traces in case of freeze.
* When the "^" character is present in the traceback, have a shortcut to jump to it or use this information to get the column where the issue lays.

(discussion with Pierre-Louis on progliste from 25/06/2022 to 27/06/2022)

**Comment by XLTechie** [comment]
Regarding the error, and jumpping to the end: may I suggest you use the comma/Shift+comma commands, as in the browse mode container start/end commands, to move to the top/bottom of tracebacks?

**Comment by CyrilleB79** [comment]
@RPTools-org, @XLTechie or anybody following this issue or repo.

I have implemented new features, among which new log reader navigation commands. The new navigation commands deal with blocks, i.e. subparts of specific logged messages. There is also a command to go to the error in a traceback frame.

Regarding blocks, for now, there are 3 types of blocks and associated messages. Below are examples:

### Block type 1: Traceback block
Located in error message, or other message logging tracebacks.

Following example with a message having 2 traceback blocks:

```
ERROR - globalPluginHandler.listPlugins (11:28:39.787) - MainThread (7868):
Error importing global plugin ndtt
Traceback (most recent call last):
  File "C:\Users\<User>\AppData\Roaming\nvda\addons\nvdaDevTestToolbox\globalPlugins\ndtt\logReader.py", line 1161, in <module>
    0/0
    ~^~
ZeroDivisionError: division by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "globalPluginHandler.pyc", line 23, in listPlugins
  File "importlib\__init__.pyc", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\<User>\AppData\Roaming\nvda\addons\nvdaDevTestToolbox\globalPlugins\ndtt\__init__.py", line 35, in <module>
    from .logReader import GlobalPlugin as LogReaderGP  # No log nor log viewer in secure mode.
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<User>\AppData\Roaming\nvda\addons\nvdaDevTestToolbox\globalPlugins\ndtt\logReader.py", line 1163, in <module>
    LogMessageHeader.makeFromLine([4,3])
  File "C:\Users\<User>\AppData\Roaming\nvda\addons\nvdaDevTestToolbox\globalPlugins\ndtt\logReader.py", line 168, in makeFromLine
    match = matchDict(RE_MESSAGE_HEADER.match(text))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'list'
```

### Block type 2: Dev info property blocks

Located in dev info message that is logged when you press `NVDA+F1` to open the log.

There are 4 blocks (or groups) of properties:
* basic properties
* appModule properties
* window properties
* interface-specific properties, e.g. IAccessible, UIA.

Message example follows:
```
INFO - globalCommands.script_navigatorObject_devInfo (11:28:41.649) - MainThread (7868):
Developer info for navigator object:
name: None
role: EDITABLETEXT
processID: 4092
roleText: None
states: MULTILINE, FOCUSABLE, FOCUSED
isFocusable: True
hasFocus: True
Python object: <NVDAObjects.Dynamic_EditableTextLogContainerIAccessibleEditWindowNVDAObject object at 0x11A0FE30>
Python class mro: (<class 'NVDAObjects.Dynamic_EditableTextLogContainerIAccessibleEditWindowNVDAObject'>, <class 'globalPlugins.ndtt.logReader.EditableTextLogContainer'>, <class 'globalPlugins.ndtt.logReader.LogContainer'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.edit.Edit'>, <class 'NVDAObjects.behaviors.EditableTextWithAutoSelectDetection'>, <class 'NVDAObjects.behaviors.EditableText'>, <class 'NVDAObjects.behaviors.EditableTextWithSuggestions'>, <class 'NVDAObjects.behaviors.InputFieldWithSuggestions'>, <class 'NVDAObjects.behaviors.EditableTextBase'>, <class 'editableText.EditableText'>, <class 'NVDAObjects.window.edit.EditBase'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <class 'garbageHandler.TrackedObject'>, <class 'object'>)
description: None
location: RectLTWH(left=17, top=81, width=1320, height=571)
value: '# -*- coding: UTF-8 -*-\r\n# NVDA Dev & Test Toolbox add-on for NVDA\r\n# Copyright (C) 2021-2025 Cyrille Bougot\r\n# This file is covered by the GNU General Public License.\r\n\r\nfrom __future__ import unicode_literals\r\n\r\nimport globalPluginHandler\r\nimport a' (truncated)
TextInfo: <class 'NVDAObjects.window.edit.EditTextInfo'>
appModule: AppModule(appModuleHandler, appName='6pad++', processID=4092)
appModule.productName: exception: No version information
appModule.productVersion: exception: No version information
appModule.helperLocalBindingHandle: c_long(79603848)
appModule.appArchitecture: 'x86'
windowHandle: 593694
windowClassName: 'Edit'
windowControlID: 7
windowStyle: 1345388996
extendedWindowStyle: 0
windowThreadID: 5596
windowText: '# -*- coding: UTF-8 -*-\r\n# NVDA Dev & Test Toolbox add-on for NVDA\r\n# Copyright (C) 2021-2025 Cyrille Bougot\r\n# This file is covered by the GNU General Public License.\r\n\r\nfrom __future__ import unicode_literals\r\n\r\nimport globalPluginHandler\r\nimport a' (truncated)
displayText: 'from pythonConsole import consoleUIif not consoleUI:return Falsereturn obj.windowHandle == consoleUI.outputCtrl.GetHandle()def isNvdaLogViewer(self, obj):hParent = winUser.getAncestor(obj.windowHandle, winUser.GA_PARENT)try:hLogViewer = gui.logViewer' (truncated)
IAccessibleObject: <POINTER(IAccessible) ptr=0xaef1268 at 119ddc60>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=593694, objectID=-4, childID=0
IAccessible accName: None
IAccessible accRole: ROLE_SYSTEM_TEXT
IAccessible accState: STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1048580)
IAccessible accDescription: None
IAccessible accValue: '# -*- coding: UTF-8 -*-\r\n# NVDA Dev & Test Toolbox add-on for NVDA\r\n# Copyright (C) 2021-2025 Cyrille Bougot\r\n# This file is covered by the GNU General Public License.\r\n\r\nfrom __future__ import unicode_literals\r\n\r\nimport globalPluginHandler\r\nimport a' (truncated)
```

### Block type 3: Python thread stack blocks

They are located in the message logged during a freeze.

```
INFO - watchdog.waitForFreezeRecovery (11:25:03.894) - watchdog (13800):
Listing stacks for Python threads:
Python stack for thread 3348 (nvwave.playWaveFile(error.wav)):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "nvwave.pyc", line 129, in play
  File "nvwave.pyc", line 339, in feed
  File "nvwave.pyc", line 316, in open
  File "nvwave.pyc", line 472, in _setVolumeFromConfig
  File "nvwave.pyc", line 441, in setVolume

Python stack for thread 6456 (watchdog.CancellableCallThread.execute(<CFunctionType object at 0x07176198>)):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "watchdog.pyc", line 428, in run
  File "threading.pyc", line 629, in wait
  File "threading.pyc", line 327, in wait

Python stack for thread 13800 (watchdog):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "watchdog.pyc", line 163, in _watcher
  File "watchdog.pyc", line 191, in waitForFreezeRecovery
  File "logHandler.pyc", line 64, in getFormattedStacksForAllThreads

Python stack for thread 8968 (winInputHook):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "winInputHook.pyc", line 108, in hookThreadFunc

Python stack for thread 19592 (UIAHandler.UIAHandler.MTAThread):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "UIAHandler\__init__.pyc", line 554, in MTAThreadFunc
  File "queue.pyc", line 171, in get
  File "threading.pyc", line 327, in wait

Python stack for thread 6584 (ThreadPoolExecutor-0_0):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "concurrent\futures\thread.pyc", line 81, in _worker

Python stack for thread 21876 (Thread-4):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "C:\Users\<User>\AppData\Roaming\nvda\addons\IBMTTS\synthDrivers\_ibmeci.py", line 383, in run
    func, args, kwargs = callbackQueue.get()
  File "queue.pyc", line 171, in get
  File "threading.pyc", line 327, in wait

Python stack for thread 22240 (Thread-3):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "C:\Users\<User>\AppData\Roaming\nvda\addons\IBMTTS\synthDrivers\_ibmeci.py", line 181, in run
    user32.GetMessageA(byref(msg), 0, 0, 0)

Python stack for thread 13256 (hwIo.ioThread.IoThread):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "hwIo\ioThread.pyc", line 264, in run

Python stack for thread 18388 (ScheduleThread):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "utils\schedule.pyc", line 90, in run

Python stack for thread 7868 (MainThread):
  File "nvda.pyw", line 309, in <module>
  File "core.pyc", line 1050, in main
  File "wx\core.pyc", line 2262, in MainLoop
  File "pythonConsole.pyc", line 509, in onInputChar
  File "pythonConsole.pyc", line 385, in execute
  File "pythonConsole.pyc", line 196, in push
  File "code.pyc", line 258, in push
  File "code.pyc", line 74, in runsource
  File "code.pyc", line 90, in runcode
  File "<console>", line 1, in <module>
```

### What you can do

Can you test (last master branch) the new commands with `O` and `L` keys and also shifted ones?
Can you let me know:
* if it works or not
* if you expect L to jump on another line, e.g. last file line in a traceback error, or erroneous code of the last frame; keep in mind the new "Go to error" command too.
* General feedback on the new navigation feature, e.g. if something is missing, if you would have done things otherwise. The UX can still change if you have good ideas.
* if you need a compiled NVDA add-on to test

Also unrelated with this issue, but not that the next release will include the following main features (most important points):
* log reader: a command to jump to the error in a traceback fram
* log reader: a command to jump to braille output messages
*
* log reader: a command to open a help message summarizing all the possible commands when log reader is active
* preserve the console input history accross restarts
* A second reverse translation command to include add-ons translations when reverse translating.

**Comment by CyrilleB79** [comment]
This issue is considered resolved in V8.0.
